function loadOrgChart(){
    const chart=`graph TD;
        CEO["Albus Dumbledore\nDirector"];
        HeadTI["Minerva McGonagall\nJefa TI"];
        HeadRRHH["Molly Weasley\nJefa RRHH"];
        HeadINV["Severus Snape\nJefe Investigaci\u00f3n"];
        HeadOP["Arthur Weasley\nJefe Operaciones"];
        HeadADM["Kingsley Shacklebolt\nJefe Administraci\u00f3n"];
        CEO-->HeadTI;
        CEO-->HeadRRHH;
        CEO-->HeadINV;
        CEO-->HeadOP;
        CEO-->HeadADM;
        HeadTI-->TI1["Hermione Granger\nDev Senior"];
        HeadTI-->TI2["Harry Potter\nSoporte"];
        HeadTI-->TI3["Ron Weasley\nRedes"];
        HeadTI-->TI4["Luna Lovegood\nQA"];
        HeadTI-->TI5["Neville Longbottom\nDBA"];
        HeadTI-->TI6["Ginny Weasley\nDevOps"];
        HeadTI-->TI7["Fred Weasley\nFrontend"];
        HeadTI-->TI8["George Weasley\nBackend"];
        HeadTI-->TI9["Cho Chang\nUX"];
        HeadTI-->TI10["Tom Riddle\nConsultor externo"];
        HeadRRHH-->HR1["Angelina Johnson\nAnalista"];
        HeadRRHH-->HR2["Katie Bell\nReclutamiento"];
        HeadRRHH-->HR3["Alicia Spinnet\nBienestar"];
        HeadRRHH-->HR4["Lee Jordan\nCapacitaci\u00f3n"];
        HeadRRHH-->HR5["Lavender Brown\nRelaciones"];
        HeadRRHH-->HR6["Pansy Parkinson\nArchivo"];
        HeadRRHH-->HR7["Draco Malfoy\nBecario"];
        HeadINV-->INV1["Alastor Moody\nInvestigador"];
        HeadINV-->INV2["Nymphadora Tonks\nInvestigadora"];
        HeadINV-->INV3["Remus Lupin\nInvestigador"];
        HeadINV-->INV4["Sirius Black\nInvestigador"];
        HeadINV-->INV5["Gilderoy Lockhart\nEspecialista"];
        HeadINV-->INV6["Rita Skeeter\nPeriodista"];
        HeadINV-->INV7["Horace Slughorn\nQu\u00edmico"];
        HeadINV-->INV8["Pomona Sprout\nBot\u00e1nica"];
        HeadINV-->INV9["Bathilda Bagshot\nHistoriadora"];
        HeadOP-->OP1["Percy Weasley\nCoordinador"];
        HeadOP-->OP2["Barty Crouch Jr.\nSupervisor"];
        HeadOP-->OP3["Barty Crouch Sr.\nLog\u00edstica"];
        HeadOP-->OP4["Dolores Umbridge\nControl Interno"];
        HeadOP-->OP5["Cornelius Fudge\nVocero"];
        HeadOP-->OP6["Cedric Diggory\nOperador"];
        HeadOP-->OP7["Viktor Krum\nOperador"];
        HeadOP-->OP8["Kingsley Shacklebolt\nTurno extra"];
        HeadADM-->ADM1["Filius Flitwick\nTesorer\u00eda"];
        HeadADM-->ADM2["Madam Hooch\nCompras"];
        HeadADM-->ADM3["Argus Filch\nMantenci\u00f3n"];
        HeadADM-->ADM4["Nearly Headless Nick\nRecepci\u00f3n"];
        HeadADM-->ADM5["Bloody Baron\nSeguridad"];
        HeadADM-->ADM6["Moaning Myrtle\nArchivo"];
        HeadADM-->ADM7["Hedwig\nMensajer\u00eda"];
        HeadADM-->ADM8["Dobby\nSoporte"];
        HeadADM-->ADM9["Kreacher\nServicios"];
        HeadADM-->ADM10["Winky\nAsistente"];
    `;
    document.getElementById('orgChart').innerHTML=`<pre class="mermaid">${chart}</pre>`;
    if(window.mermaid){mermaid.init(undefined, '#orgChart .mermaid');}
}
